### ISSUE TITLE
Error in pynq-z2

### ISSUE THREAD

**Issue by chenstarx** [mohdumar644/TinyYOLO-BNN#4]
Hi, I have tried your code in pynq-z2, but every time when running the line
hw_classifier = bnn.CnvClassifier(bnn.NETWORK_CNVW1A1,'tinyyolo',bnn.RUNTIME_HW)
the jupyter would be died.
So I ran the code with bash, and the terminal return some info:
Setting network weights and thresholds in accelerator...
terminate called after throwing an instance of 'char const*'
Aborted
This error may from bnn/src/network/cnvW1A1/main_python.cpp
Or maybe I just did wrong, do you know how to solve this? thanks very much!

**Comment by mohdumar644** [comment]
The bitstream is provided for the ZC706 board only.
It is not possible to fit it on PYNQ-Z1/2
